name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
    paths:
      - '.github/deploy.yaml'
  workflow_dispatch:  # Allows manual deployment via GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.3.0' # Match the Node.js version with your Astro project

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SURVEILR_GITHUB_TOKEN }}
          publish_dir: ./dist  # The directory where Astro outputs static files
