name: Run Deno and Push Generated SQL

on:
  push:
    paths:
      - 'lib/service/qualityfolio/*.sql.ts'

jobs:
  run-deno:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Trigger qualityfolio workflow
      run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
         /repos/var.OWNER/var.REPO/actions/workflows/var.WORKFLOW_ID/dispatches \
        -d '{"ref":"main"}'
