name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      pages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker buildx build \
             --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
             --build-arg EG_SURVEILR_COM_IMAP_FOLDER=${{ secrets.EG_SURVEILR_COM_IMAP_FOLDER }} \
             --build-arg EG_SURVEILR_COM_IMAP_USER_NAME=${{ secrets.EG_SURVEILR_COM_IMAP_USER_NAME }} \
             --build-arg EG_SURVEILR_COM_IMAP_PASS=${{ secrets.EG_SURVEILR_COM_IMAP_PASS }} \
             --build-arg EG_SURVEILR_COM_IMAP_HOST=${{ secrets.EG_SURVEILR_COM_IMAP_HOST }} \
             -t ghcr.io/surveilr/www.surveilr.com/omnibus-rssd-nginx:latest \
             -f support/deploy/omnibus-rssd-nginx.dockerfile \
             --push \
             .

      - name: Push Docker image
        run: |
          docker push ghcr.io/surveilr/www.surveilr.com/omnibus-rssd-nginx:latest
