name: Qualityfolio Workflow-Trigger

on:
  push:
    paths:
      - 'lib/service/qualityfolio/*.sql.ts'
  workflow_dispatch:    

jobs:
  run-deno:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Trigger qualityfolio workflow
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ vars.OWNER }}/${{ vars.REPO }}/actions/workflows/${{ vars.WORKFLOW_ID }}/dispatches \
        -d '{"ref":"main"}'

